-- =========================================
-- # CALC. DE REPRESENTATIVIDADE ACUMULADA
-- =========================================

SELECT 
	  *
	 -- OBTENDO A REPRESENTATIVIDADE ACUMULADA DA QUANTIDADE DE VENDAS
	, SUM(RPR_VENDAS) OVER(ORDER BY DATA ASC) RPR_ACUM_VENDAS

	 -- OBTENDO A REPRESENTATIVIDADE ACUMULADA DO VALOR DA VENDA 
	, SUM(RPR_VALOR) OVER(ORDER BY DATA ASC) RPR_ACUM_VALOR
FROM 
(
	SELECT 
		  *
		  -- OBTENDO A REPRESENTATIVIDADE DA QUANTIDADE DE VENDAS
		, ROUND(CONVERT(FLOAT,QTDE_VENDAS) / (SUM(QTDE_VENDAS) OVER(PARTITION BY 1)),2) RPR_VENDAS
	
		  -- OBTENDO A REPRESENTATIVIDADE DO VALOR DA VENDA
		, ROUND(VALOR / (SUM(VALOR) OVER(PARTITION BY 1)),2) RPR_VALOR
	FROM TB_VENDAS WITH(NOLOCK)
) A