DROP TABLE IF EXISTS ##VENDAS;
CREATE TABLE ##VENDAS ([CLIENTE] VARCHAR(30), [PRODUTO] VARCHAR(10), [DATA] DATE);

BULK INSERT ##VENDAS FROM 'C:\Users\GABRIEL\Downloads\info_vendas.csv'
	WITH
	(
		FIELDTERMINATOR=';',
		FIRSTROW=2,
		CODEPAGE = 65001
	);
	

DECLARE @OFFSET INT = 0, @LOTE INT = 1, @INFO_PV VARCHAR(MAX);

WHILE 1=1

BEGIN
	SELECT 
		@INFO_PV = CONCAT(@INFO_PV,'[',[DATA],']',',') 
	
	FROM 
	(
		SELECT 
			DISTINCT [DATA] 
		FROM ##VENDAS
	) A
	
	ORDER BY [DATA] ASC
	
	OFFSET @OFFSET ROWS
	FETCH NEXT @LOTE ROWS ONLY;

	IF @@ROWCOUNT = 0
		BREAK;
	
	SET @OFFSET+=1;

END

SET @INFO_PV = LEFT(@INFO_PV,LEN(@INFO_PV)-1)

DECLARE @SQL_PV VARCHAR(MAX) = '
SELECT * FROM
(
	SELECT * 
	FROM ##VENDAS) SUB
PIVOT (COUNT(CLIENTE) FOR DATA IN('+@INFO_PV+')) PV';

EXEC (@SQL_PV)

INSERT INTO ##VENDAS (CLIENTE, PRODUTO, DATA) VALUES ('MARIA','P_02',CAST(CURRENT_TIMESTAMP AS DATE))